apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: sureshkhanishk/frontend:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            #limits: is greater than or equal to requests,
          limits:
            memory: "128Mi"
            cpu: "100m"

--- 
kind: Service 
apiVersion: v1
metadata:
  name: frontend  
  namespace: expense 
spec: 
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
    - name: frontend-port
      port: 80
      protocol: TCP
      targetPort: 80
