apiVersion: v1 
kind: ConfigMap 
metadata:
  name: backend 
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: sureshkhanishk/backend:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            #limits: is greater than or equal to requests,
          limits:
            memory: "128Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: backend 


--- 
kind: Service 
apiVersion: v1
metadata:
  name: backend  
  namespace: expense 
spec: 
  selector:
    app: backend
    tier: api
    project: expense
  ports:
    - name: backend-port
      port: 8080
      protocol: TCP
      targetPort: 8080
